### ISSUE TITLE
node-touch is noisy

### ISSUE THREAD

**Issue by guncha** [isaacs/node-touch#22]
Another dependency installed `node-touch` in my node modules so now I can't call the unix version from my `package.json` scripts and am stuck with it. The only real difference is that `node-touch` error logs the returned `fs.stat` object. Can this not be the default behavior?

**Comment by jeffmoss** [comment]
@isaacs: Why have a bin/touch at all? What purpose does it serve?

**Comment by guncha** [comment]
It makes sense for platforms like Windows that lack the `touch` command. This way node scripts can depend on it being available. Still, it should at least act like the unix version and be quiet unless asked.

**Comment by demurgos** [comment]
I strongly agree. I just updated `typings-core` and it comes with `touch`. Now, every `touch` I do emits the stats.

**Comment by thiagodebastos** [comment]
@demurgos I was having the same issue, I didn't even know how I got this in my global npm/yarn. It took me a while to figure out where the stats were coming from and it never occured to me to check if my Mac's `touch` command had been highjacked.

I found the Stats function here:
https://npmdoc.github.io/node-npmdoc-s3fs/build/apidoc.html#apidoc.element.s3fs.Stats

**Comment by raxod502** [comment]
If node-touch provides a CLI, then it should emulate the universal standard for `touch(1)`. Currently the only way to avoid the output is to redirect stderr, which obviously disables any error reporting. I can't even make my own `touch` binary to redirect to the system-provided one, since `node_modules/.bin` comes earlier in the `PATH` than the system directories.

**Comment by jeffmoss** [comment]
The noise is one thing. I also see it as an unnecessary security risk. I don't think standard system commands should EVER be overridden by a package, it ought to be strictly forbidden, especially when there is no obvious reason for it. Some malicious code could be executed this way by an uninformed technician.

The fix I propose is a new command called "nodetouch" as long as it isn't "touch" or "cp" or anything like that, it's fine if people are executing .bin/ code as long as there are no surprises.

I'm a little concerned that this even needs to be pointed out honestly, @isaacs.

**Comment by guncha** [comment]
@jeffmoss how could this possibly be a security risk?

**Comment by jeffmoss** [comment]
Well I went to run touch and instead it executed some javascript code that I'd just downloaded from the internet. If I am a hacker, if I ever need to gain access to a remote system, the system is secured but I have some control over the javascript/packages then this will make it much easier to execute malicious code.

**Comment by guncha** [comment]
Any NPM package can already run arbitrary code when it's installed. There's no need for this trickery you are describing.

**Comment by raxod502** [comment]
Not that this necessarily matches a real-world situation, but I don't think having statistics about the filesystem unexpectedly written to log files is ideal from a security perspective either.

**Comment by jeffmoss** [comment]
@guncha It's difficult to explain exactly why it is a security hole, I can't give you any real-world scenarios, I think it's more of a "slippery slope" thing. If the NPM package (through it's deps) overrides your touch command then what's to stop someone else from overriding the chown command? Maybe someone eventually adds a "bash" replacement that steals all your passwords. Something is happening that nobody would ever expect to happen, and someone who's very concerned with WHO and WHAT is operating on a particular machine wants to trust that trojan horses won't ever be activated by something npm-related.

With system package managers like Aptitude you have to manually adjust the pool of packages and allow those maintained by the community, otherwise all you get is "secure" official packages that you can trust. NPM needs to treat every package as though it's insecure and contains exploits, since everything is maintained by the community.

**Comment by isaacs** [comment]
Fixed on v2
